/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package reproductorpi_tyn;

import javax.swing.ImageIcon;
import javax.swing.Timer;

/**
 *
 * @author yosnavmol
 */
public class Reproductor extends javax.swing.JFrame {

    String imgAlbum = "/img/Album1.jpg";
    String imgPausa = "/img/Pausa.png";
    String imgPlay = "/img/Play.png";

    private int duracion = 100;
    private Timer timer;

    private int reprCounter;
    private boolean isReproducing = false;

    public int getReprCounter() {
        return reprCounter;
    }

    public void setReprCounter(int reprCounter) {
        this.reprCounter = reprCounter;
    }

    public boolean isIsReproducing() {
        return isReproducing;
    }

    public void setIsReproducing(boolean isReproducing) {
        this.isReproducing = isReproducing;
    }

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Reproductor.class.getName());

    /**
     * Creates new form Reproductor
     */
    public Reproductor() {
        initComponents();

        pbReproduction.setMaximum(duracion); // le asignamos un valor tope al ProgressBar

        /**
         * Creamos un timer cuya finalidad es ejecutarse cada segundo para ir
         * avanzando el ProgressBar y el jlabel contador.
         */
        timer = new javax.swing.Timer(1000, (e) -> {
            if (isReproducing) {
                reprCounter++;
                /**
                 * Si llega al final se pausa automaticamente, cambia el
                 * lbEstado y el btnToggle a false y el icono.
                 */
                if (reprCounter >= duracion) {
                    reprCounter = duracion;
                    timer.stop();
                    isReproducing = false;
                    lbEstado.setText("Estado: Terminado");
                    btnTogglePlayPause.setSelected(false);
                    btnTogglePlayPause.setIcon(new ImageIcon(getClass().getResource(imgPlay)));
                }
                /**
                 * Aqui actualizamos el progressbar y el lbContador cada
                 * segundo.
                 */
                pbReproduction.setValue(reprCounter);
                lbContador.setText("00:" + String.format("%02d", reprCounter));
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbAlbum = new javax.swing.JLabel();
        btnStop = new javax.swing.JButton();
        slVolume = new javax.swing.JSlider();
        btnTogglePlayPause = new javax.swing.JToggleButton();
        pbReproduction = new javax.swing.JProgressBar();
        lbEstado = new javax.swing.JLabel();
        lbContador = new javax.swing.JLabel();
        lbVolDown = new javax.swing.JLabel();
        lbVolUp = new javax.swing.JLabel();
        lbShowVolume = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbAlbum.setBackground(new java.awt.Color(0, 0, 0));
        lbAlbum.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Album1.jpg"))); // NOI18N

        btnStop.setBackground(new java.awt.Color(0, 0, 0, 0));
        btnStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Parada.png"))); // NOI18N
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });

        slVolume.setMajorTickSpacing(5);
        slVolume.setMinorTickSpacing(1);
        slVolume.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slVolumeStateChanged(evt);
            }
        });

        btnTogglePlayPause.setBackground(new java.awt.Color(0, 0, 0, 0));
        btnTogglePlayPause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Play.png"))); // NOI18N
        btnTogglePlayPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTogglePlayPauseActionPerformed(evt);
            }
        });

        lbEstado.setText("Estado: Pausado");

        lbContador.setText("00:00");

        lbVolDown.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbVolDown.setText("-");

        lbVolUp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbVolUp.setText("+");

        lbShowVolume.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbShowVolume.setText("50");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(btnTogglePlayPause, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnStop, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbVolDown, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(lbShowVolume, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbVolUp, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(slVolume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(lbAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbEstado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbContador))
                    .addComponent(pbReproduction, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(117, 117, 117))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lbAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEstado)
                    .addComponent(lbContador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pbReproduction, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTogglePlayPause, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStop, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(slVolume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbVolDown)
                            .addComponent(lbVolUp)
                            .addComponent(lbShowVolume))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTogglePlayPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTogglePlayPauseActionPerformed
        if (btnTogglePlayPause.isSelected()) {
            isReproducing = true;
            lbEstado.setText("Estado: Reproduciendo");
            btnTogglePlayPause.setIcon(new ImageIcon(getClass().getResource(imgPausa)));

            if (!timer.isRunning()) {
                timer.start();
            }

        } else {
            isReproducing = false;
            lbEstado.setText("Estado: Pausado");
            btnTogglePlayPause.setIcon(new ImageIcon(getClass().getResource(imgPlay)));
        }
    }//GEN-LAST:event_btnTogglePlayPauseActionPerformed

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        reprCounter = 0;
        isReproducing = false;

        timer.stop();

        pbReproduction.setValue(0);
        lbContador.setText("00:00");
        lbEstado.setText("Estado: Detenido");

        btnTogglePlayPause.setSelected(false);
        btnTogglePlayPause.setIcon(new ImageIcon(getClass().getResource(imgPlay)));
    }//GEN-LAST:event_btnStopActionPerformed

    private void slVolumeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slVolumeStateChanged
        lbShowVolume.setText(String.valueOf(slVolume.getValue()));
    }//GEN-LAST:event_slVolumeStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Reproductor().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStop;
    private javax.swing.JToggleButton btnTogglePlayPause;
    private javax.swing.JLabel lbAlbum;
    private javax.swing.JLabel lbContador;
    private javax.swing.JLabel lbEstado;
    private javax.swing.JLabel lbShowVolume;
    private javax.swing.JLabel lbVolDown;
    private javax.swing.JLabel lbVolUp;
    private javax.swing.JProgressBar pbReproduction;
    private javax.swing.JSlider slVolume;
    // End of variables declaration//GEN-END:variables
}
